""" Version/author information """
__version__ = "3.2"
__author__ = "Adrian Pueyo (Ported to Nuke 16/PySide6 by Kire Timov)"
__date__ = "Jan 15 2026"
__mail__ = "pueyovfx@gmail.com"
__web__ = "www.adrianpueyo.com"